

#########################
## load all r packages ##
#########################

library(knitr)
library(xlsx)
library(ggplot2)
library(tableone)
library(plyr)
library(dplyr)
library(lme4)
library(party)
library(randomForest)
library(caret)
library(Hmisc)
library(tableone)
library(survival)
library(lattice)
library(cluster) 
library(fpc)
library(NbClust)
library(flexclust)
library(pvclust)
library(ggdendro)
library(plotly)
library(reshape)
library(webshot)
library(xtable)
library(shiny)
library(lmerTest)
library(ordinal)
library(texreg)
library(tidyr)
library(scales)
library(tableone)
library(survival)
library(memisc)
library(RCurl)
